version: "3.8"

services:
  app:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_DATABASE_URL=${NEXT_PUBLIC_DATABASE_URL}
      - AUTH_DRIZZLE_URL=${AUTH_DRIZZLE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - JWT_ENCRYPTION_KEY=${JWT_ENCRYPTION_KEY}
      - JWT_MAX_AGE=${JWT_MAX_AGE}
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codevisualizer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
