# docker/java/Dockerfile
FROM openjdk:17-slim

WORKDIR /app

# Download Jackson Databind library for JSON processing
RUN apt-get update && \
    apt-get install -y wget && \
    wget -O jackson-databind.jar https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.0/jackson-databind-2.13.0.jar && \
    wget -O jackson-core.jar https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.0/jackson-core-2.13.0.jar && \
    wget -O jackson-annotations.jar https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.0/jackson-annotations-2.13.0.jar

COPY ./docker/java/JavaExecutor.java /app/
RUN javac -cp .:jackson-databind.jar:jackson-core.jar:jackson-annotations.jar JavaExecutor.java

CMD ["java", "-cp", ".:jackson-databind.jar:jackson-core.jar:jackson-annotations.jar", "JavaExecutor"]
